version: 2
jobs:
  build:
    docker:
      - image: ribakov/workspace:2017.3.0p2
    steps:
      - checkout
      - run:
          name: Fetch dependencies
          command: nuget restore SolucionTutor.sln
      - run:
          name: Build
          command: msbuild
      - run:
          name: Test Reactive Tutor
          command: nunit3-console ./TutoringModule/ReactiveTutor/Its.TutoringModule.ReactiveTutorTest/bin/Debug/Its.TutoringModule.ReactiveTutorTest.dll --noresult